#
version: '3.7'

services:
  whitelink:
    build: .
    # Custom command which adds --reload
    command: ["gunicorn", "-w", "3", "-b", "0.0.0.0:8000", "--reload", "whitelink.wsgi"]
    environment:
      DEBUG: "on"
      SECRET_KEY: helloworld
      DATABASE_URL: postgres://whitelink:whitelink@db/whitelink
    volumes:
    - .:/app
    ports:
    - 8000:8000
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: whitelink
      POSTGRES_PASSWORD: whitelink
      POSTGRES_DB: whitelink
